// ============================================================
// discoverySample.js — sample discovery response used as a fallback
// preview when the live agents service returns no results. Mirrors the
// real envelope shape ({ cloudProvider, executionTime, results: [...] }).
// ============================================================
export const DISCOVERY_SAMPLE = {
  requestId: 'req-7B94D4A3BBFB',
  projectId: 'project-456',
  userId: 'user-123',
  cloudProvider: 'AZURE',
  executionTime: '2026-06-26T14:06:44.089356',
  status: 'PARTIAL',
  summary: {
    totalAgentsRequested: 2,
    totalAgentsExecuted: 2,
    successfulAgents: 1,
    failedAgents: 1,
  },
  results: [
    {
      agentId: 'azure_discovery',
      agentType: 'dynamic',
      version: '1.0.0',
      status: 'SUCCESS',
      data: {
        agent_id: 'azure_discovery',
        agent_type: 'dynamic',
        version: '1.0.0',
        recommendations: {
          status: 'SUCCESS',
          cloudProvider: 'AZURE',
          executionTime: '2026-06-26T14:06:44.069288Z',
          requestId: 'req-DD3B4F3B55DA',
          projectId: 'project-456',
          userId: 'user-123',
          accounts: [
            {
              id: '53f91f0e-93ff-4b7a-9c63-ecb3b299a348',
              name: 'Production Subscription',
              type: 'subscription',
              provider: 'AZURE',
              categories: [
                {
                  id: 'compute',
                  name: 'Compute',
                  resources: [
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/dn-langfuse/providers/Microsoft.Compute/virtualMachines/datanext-v3-app',
                      name: 'datanext-v3-app',
                      resourceType: 'VirtualMachine',
                      properties: {
                        region: 'centralindia',
                        resourceGroup: 'dn-langfuse',
                        state: 'Unknown',
                        size: 'Standard_D4as_v5',
                        os: 'Linux',
                        health: 'Healthy',
                      },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/DN-LANGFUSE/providers/Microsoft.Compute/virtualMachines/DATANEXT-V3-APP/extensions/AADSSHLoginForLinux',
                      name: 'AADSSHLoginForLinux',
                      resourceType: 'VirtualMachine',
                      properties: {
                        region: 'centralindia',
                        resourceGroup: 'dn-langfuse',
                        state: 'Unknown',
                        size: '',
                        os: 'Linux',
                        health: 'Healthy',
                      },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/dn-langfuse/providers/Microsoft.Compute/virtualMachines/datanext-v3-app/extensions/AzurePolicyforLinux',
                      name: 'AzurePolicyforLinux',
                      resourceType: 'VirtualMachine',
                      properties: {
                        region: 'centralindia',
                        resourceGroup: 'dn-langfuse',
                        state: 'Unknown',
                        size: '',
                        os: 'Linux',
                        health: 'Healthy',
                      },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/dn-langfuse/providers/Microsoft.Compute/virtualMachines/datanext-v3-app/extensions/enablevmAccess',
                      name: 'enablevmAccess',
                      resourceType: 'VirtualMachine',
                      properties: {
                        region: 'centralindia',
                        resourceGroup: 'dn-langfuse',
                        state: 'Unknown',
                        size: '',
                        os: 'Linux',
                        health: 'Healthy',
                      },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/ey-datanext-runner-rg/providers/Microsoft.Compute/virtualMachines/datanext-runner-vm',
                      name: 'datanext-runner-vm',
                      resourceType: 'VirtualMachine',
                      properties: {
                        region: 'centralindia',
                        resourceGroup: 'ey-datanext-runner-rg',
                        state: 'Unknown',
                        size: 'Standard_D4s_v3',
                        os: 'Linux',
                        health: 'Healthy',
                      },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/x-ops/providers/Microsoft.Compute/virtualMachines/xops--vm01',
                      name: 'xops--vm01',
                      resourceType: 'VirtualMachine',
                      properties: {
                        region: 'centralindia',
                        resourceGroup: 'x-ops',
                        state: 'Unknown',
                        size: 'Standard_D2s_v3',
                        os: 'Linux',
                        health: 'Healthy',
                      },
                    },
                  ],
                  count: 6,
                },
                {
                  id: 'storage',
                  name: 'Storage',
                  resources: [
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/databricks_cost_analysis/providers/Microsoft.Storage/storageAccounts/databrickslabxx',
                      name: 'databrickslabxx',
                      resourceType: 'StorageAccount',
                      properties: { region: 'eastus', resourceGroup: 'databricks_cost_analysis', sku: '' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/ey-datanext-dev-rg/providers/Microsoft.Storage/storageAccounts/dnblobaccount',
                      name: 'dnblobaccount',
                      resourceType: 'StorageAccount',
                      properties: { region: 'centralindia', resourceGroup: 'ey-datanext-dev-rg', sku: '' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/ey-datanext-dev-rg/providers/Microsoft.Storage/storageAccounts/eydatanextv4state',
                      name: 'eydatanextv4state',
                      resourceType: 'StorageAccount',
                      properties: { region: 'centralindia', resourceGroup: 'ey-datanext-dev-rg', sku: '' },
                    },
                  ],
                  count: 3,
                },
                {
                  id: 'database',
                  name: 'Databases',
                  resources: [
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/ey-datanext-dev-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/dn-pg-server',
                      name: 'dn-pg-server',
                      resourceType: 'PostgreSQL',
                      properties: { region: 'centralindia', resourceGroup: 'ey-datanext-dev-rg', version: '16' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/ey-datanext-dev-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/dn-pg-server-backup',
                      name: 'dn-pg-server-backup',
                      resourceType: 'PostgreSQL',
                      properties: { region: 'centralindia', resourceGroup: 'ey-datanext-dev-rg', version: '16' },
                    },
                  ],
                  count: 2,
                },
                {
                  id: 'network',
                  name: 'Networking',
                  resources: [
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/datanext-v3-app_group/providers/Microsoft.Network/networkSecurityGroups/datanext-v3-app-nsg',
                      name: 'datanext-v3-app-nsg',
                      resourceType: 'NetworkSecurityGroup',
                      properties: { region: 'centralindia', resourceGroup: 'datanext-v3-app_group' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/datanext-v3-app_group/providers/Microsoft.Network/publicIPAddresses/datanext-v3-app-ip',
                      name: 'datanext-v3-app-ip',
                      resourceType: 'PublicIP',
                      properties: { resourceGroup: 'datanext-v3-app_group' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/dn-langfuse/providers/Microsoft.Network/publicIPAddresses/langfuse-frontend',
                      name: 'langfuse-frontend',
                      resourceType: 'PublicIP',
                      properties: { resourceGroup: 'dn-langfuse' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/dn-langfuse/providers/Microsoft.Network/virtualNetworks/vnet-centralindia-2',
                      name: 'vnet-centralindia-2',
                      resourceType: 'VirtualNetwork',
                      properties: { region: 'centralindia', resourceGroup: 'dn-langfuse' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/ey-datanext-runner-rg/providers/Microsoft.Network/networkSecurityGroups/datanext-runner-vm-nsg',
                      name: 'datanext-runner-vm-nsg',
                      resourceType: 'NetworkSecurityGroup',
                      properties: { region: 'centralindia', resourceGroup: 'ey-datanext-runner-rg' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/ey-datanext-runner-rg/providers/Microsoft.Network/publicIPAddresses/datanext-runner-vm-ip',
                      name: 'datanext-runner-vm-ip',
                      resourceType: 'PublicIP',
                      properties: { resourceGroup: 'ey-datanext-runner-rg' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/ey-datanext-runner-rg/providers/Microsoft.Network/virtualNetworks/datanext-runner-vm-vnet',
                      name: 'datanext-runner-vm-vnet',
                      resourceType: 'VirtualNetwork',
                      properties: { region: 'centralindia', resourceGroup: 'ey-datanext-runner-rg' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/x-ops/providers/Microsoft.Network/networkSecurityGroups/xops--vm01-nsg',
                      name: 'xops--vm01-nsg',
                      resourceType: 'NetworkSecurityGroup',
                      properties: { region: 'centralindia', resourceGroup: 'x-ops' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/X-OPS/providers/Microsoft.Network/publicIPAddresses/xops--vm01-ip',
                      name: 'xops--vm01-ip',
                      resourceType: 'PublicIP',
                      properties: { resourceGroup: 'x-ops' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/X-OPS/providers/Microsoft.Network/virtualNetworks/xops--vm01-vnet',
                      name: 'xops--vm01-vnet',
                      resourceType: 'VirtualNetwork',
                      properties: { region: 'centralindia', resourceGroup: 'x-ops' },
                    },
                  ],
                  count: 10,
                },
                { id: 'containers', name: 'Containers', resources: [], count: 0 },
                {
                  id: 'other',
                  name: 'Other',
                  resources: [
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/databricks_cost_analysis/providers/Microsoft.Databricks/workspaces/databricks-cost-lab',
                      name: 'databricks-cost-lab',
                      resourceType: 'workspaces',
                      properties: { region: 'eastus', resourceGroup: 'databricks_cost_analysis' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/DATANEXT-V3-APP_GROUP/providers/Microsoft.Compute/disks/datanext-v3-app_OsDisk_1_9f0270d77b7f424d9ec5e052026296a1',
                      name: 'datanext-v3-app_OsDisk_1_9f0270d77b7f424d9ec5e052026296a1',
                      resourceType: 'disks',
                      properties: { region: 'centralindia', resourceGroup: 'datanext-v3-app_group' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/datanext-v3-app_group/providers/Microsoft.Network/networkInterfaces/datanext-v3-app436_z1',
                      name: 'datanext-v3-app436_z1',
                      resourceType: 'networkinterfaces',
                      properties: { region: 'centralindia', resourceGroup: 'datanext-v3-app_group' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/dn-containers/providers/Microsoft.RecoveryServices/vaults/vault-mn4j0h3t',
                      name: 'vault-mn4j0h3t',
                      resourceType: 'vaults',
                      properties: { region: 'centralindia', resourceGroup: 'dn-containers' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/dn-langfuse/providers/Microsoft.Compute/sshPublicKeys/manish-ssh',
                      name: 'manish-ssh',
                      resourceType: 'sshpublickeys',
                      properties: { region: 'centralindia', resourceGroup: 'dn-langfuse' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/dn-langfuse/providers/Microsoft.Network/applicationGateways/langfuse-gateway',
                      name: 'langfuse-gateway',
                      resourceType: 'applicationgateways',
                      properties: { region: 'centralindia', resourceGroup: 'dn-langfuse' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/ey-datanext-api_group/providers/Microsoft.CognitiveServices/accounts/ey-datanext-claude',
                      name: 'ey-datanext-claude',
                      resourceType: 'accounts',
                      properties: { region: 'centralindia', resourceGroup: 'ey-datanext-api_group' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/ey-datanext-dev-rg/providers/Microsoft.App/containerApps/backend-app-dev',
                      name: 'backend-app-dev',
                      resourceType: 'containerapps',
                      properties: { region: 'centralindia', resourceGroup: 'ey-datanext-dev-rg' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/ey-datanext-dev-rg/providers/Microsoft.App/containerApps/frontend-app-dev',
                      name: 'frontend-app-dev',
                      resourceType: 'containerapps',
                      properties: { region: 'centralindia', resourceGroup: 'ey-datanext-dev-rg' },
                    },
                    {
                      id: '/subscriptions/53f91f0e-93ff-4b7a-9c63-ecb3b299a348/resourceGroups/ey-datanext-dev-rg/providers/Microsoft.ContainerRegistry/registries/datanextdevacr',
                      name: 'datanextdevacr',
                      resourceType: 'registries',
                      properties: { region: 'eastus', resourceGroup: 'ey-datanext-dev-rg' },
                    },
                  ],
                  count: 36,
                },
              ],
              summary: { regions: 6, resourceGroups: 13, totalResources: 57 },
              health: { healthy: 8, unhealthy: 1 },
              insights: [],
            },
          ],
          summary: { totalAccounts: 1, totalResources: 57, regions: 6 },
          insights: [],
        },
        validation: true,
      },
      error: null,
    },
    {
      agentId: 'azure_netowk',
      agentType: 'unknown',
      version: 'unknown',
      status: 'FAILED',
      data: null,
      error: "'Unknown agent_id: azure_netowk'",
    },
  ],
};
